In [ ]:
import numpy as np


In [20]:
numbers = np.array([1,2,3,4,5,6,7])
print(numbers)

[1 2 3 4 5 6 7]


In [21]:
points = np.array([[1,2,3],[4,5,6]])
print(points)

[[1 2 3]
 [4 5 6]]


In [27]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [34]:
print(arr[0,1,2])

6


In [42]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr1[1:5:2])

[2 4]


In [43]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr2[1, 1:4])

[7 8 9]


In [47]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [45]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [48]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [49]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [50]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [51]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [52]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)


b'1'
b'2'
b'3'


In [54]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [55]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [56]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [58]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [59]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [2]:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [3]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [13]:
arr= np.array([[1,2,3],[8,9,5]])
print(arr.shape)

(2, 3)


In [11]:
for element in arr:
    if element[0] > 45:
        print("Greater than 45")
    else:
        print("Less than 45!")

Less than 45!
Less than 45!


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
mult = newarr * 5
print(mult)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]]


In [23]:

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [24]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [25]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [29]:
arr1 = np.array([2,4,6])
arr2 = np.array([1,3,5])
new_arr = np.concatenate((arr1, arr2))
print(new_arr)
sort_arr = np.sort(new_arr)
print(sort_arr)

[2 4 6 1 3 5]
[1 2 3 4 5 6]


In [30]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [34]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [40]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print(newarr)
sort = np.sort(newarr)
print(sort)

[array([1, 2, 3]), array([4, 5, 6])]
[[1 2 3]
 [4 5 6]]


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [42]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [46]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)
y = np.where(arr == 7)

print(x)
print(y)

1
(array([1], dtype=int64),)


In [50]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [51]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [53]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [79]:
physics_marks = np.array([75,85,91,42,46,65,35])
chemistry_marks = np.array([83,47,92,56,60,43,30])
conc_marks = np.concatenate((physics_marks, chemistry_marks))
sort_marks = np.sort(conc_marks)
filter_marks = []
for mark in sort_marks:
    if mark > 50:
        filter_marks.append(True)
    else:
        filter_marks.append(False)
new_marks = sort_marks[filter_marks]
print(filter_marks)
print("Marks above 45: ",new_marks)
print(new_marks.reshape(2,4))

[False, False, False, False, False, False, True, True, True, True, True, True, True, True]
Marks above 45:  [56 60 65 75 83 85 91 92]
[[56 60 65 75]
 [83 85 91 92]]


# Random Number

In [69]:
from numpy import random

In [83]:
x = random.randint(100, size=(10))

print(x)

[26 93 24 43 65 48 55 24 40 50]


In [85]:
x = random.rand(4)

print(x)

[0.45820535 0.23803996 0.5557693  0.70656783]


In [100]:
user = int(input("Enter a positive number to generate random numbers for you: "))
user_range = int(input("Enter range from 0 to :"))
user_rand = random.randint(user, size=(user_range))
print("Random numbers: \n", user_rand)

Enter a positive number to generate random numbers for you: 50
Enter range from 0 to :10
Random numbers: 
 [ 9 23 43 35 25 36  3  7 39 17]


In [93]:
x = random.rand(3, 5)

print(x)

[[0.86639873 0.14397313 0.67247517 0.24578935 0.86861218]
 [0.46349312 0.90598849 0.47607625 0.5194941  0.19054025]
 [0.16836444 0.98634543 0.73509905 0.86159391 0.3265903 ]]


In [98]:
x = random.choice([3, 5, 7, 9])

print(x)

7


In [99]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 3 3 7 3]
 [3 9 7 5 9]
 [5 7 7 9 9]]


# Data Distribution

In [108]:
x = random.choice([3, 5, 7, 9], p=[0.3, 0.1, 0.4, 0.2], size=(3,4))

print(x)

[[9 7 3 9]
 [7 3 7 3]
 [7 9 9 7]]


In [109]:
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[3 4 5 2 1]


In [110]:
arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[1 2 4 5 3]


# Visualize Distributions With Seaborn